### ISSUE TITLE
Access to admin routes without login caused FatalThrowableError

### ISSUE THREAD

**Issue by aaranta** [sarthaksavvy/laravel-multiauth#27]
For instance, after we added @admin('editor') to the post.blade.php, if we tried to access this route without login, FatalThrowableError will occur.
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function roles() on null

This happens to routes with 'super' role too,
Of course if we access the routes after login, it will be fine.

**Comment by sarthaksavvy** [comment]
have you updated this package, I have covered this issue.

**Comment by kiharani101** [comment]
Try make the default laravel auth. In that case it will properly redirect. I had the same same issue too.

**Comment by kiharani101** [comment]
And then Sarthak, how can I extend the admin routes with a controller in the usual namespace? Like I have a products controller and would like admins have access to /admin/products?

**Comment by sarthaksavvy** [comment]
@kiharani101 you can simply create a route like route::get('/admin/products')
this route can be on web.php or you can publish package admin.php route file into your project route folder.

Then you can use middleware define in this package to protect that route and only accessed by admins.
