### ISSUE TITLE
Migration Rollback Error

### ISSUE THREAD

**Issue by aaranta** [sarthaksavvy/laravel-multiauth#31]
php artisan migrate:rollback returns error. Not able to drop the Multiauth "admins" table.

[Logs]
...
Rolling back: 2017_03_06_053834_create_admin_role_table
Rolled back:  2017_03_06_053834_create_admin_role_table
Rolling back: 2017_03_06_023521_create_admins_table

Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (SQL: drop table if exists `admins`)

  at ..\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }

Did I do anything wrongly? Please advise.
Thanks.

**Comment by sarthaksavvy** [comment]
try to use 'php artisan migrate:fresh'

**Comment by sarthaksavvy** [comment]
Fixed !
